### ISSUE TITLE
Intelligente drievoudige warmtepomp 

### ISSUE THREAD

**Issue by garfiel1** [Xenomes/Domoticz-TinyTUYA-Local-Plugin#1]
Intelligent Heat Pump
[devices.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin/files/14722045/devices.json)
[snapshot.json](https://github.com/Xenomes/Domoticz-TinyTUYA-Local-Plugin/files/14722072/snapshot.json)

**Comment by Xenomes** [comment]
Thanks for the JSON! Found small bug and added the devices mentioned ad the Cloud plugin.
